version: '3.8'

services:
  file_scanner:
    build: .
    container_name: dosya_guvenlik_tarama
    volumes:
      - ./watch:/app/watch:rw  # Ensure this is writable
      - ./results:/app/results:rw  # Ensure this is writable
    environment:
      - VIRUSTOTAL_API_KEY=your_virustotal_api_key
    ports:
      - "5001:5001"  # Map port 5000 in the container to port 5000 on the host
    command: python main.py
